#!/bin/bash
declare -r ROOT=0

if [ $UID -ne $ROOT ]; then
    printf "\n\tYou must run this script as privileged user\n\n"
    exit 121
fi

if [ ! -e "$1" ]; then
    userName=$(cat /etc/passwd | grep -E "\b($1)\b" | awk -F : '{print $1}')

    if [ -z "$userName" ]; then
        printf "\n%s\n\n" "$(color -r "$(blink.sh "Username ${1^^} does not exist!")")"
        exit 119
    else
        # usermod -aG sudo "$userName"
        exit 0
    fi
else
    printf "\nMust enter a valid username\n\n"
    exit 120
fi
